name: Docker Image CI

on:
  push:
    tags:
       - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag yabramkin/aws-cdk-runtime-environment-win:${{steps.tag.outputs.tag}}
