name: Docker Image CI

on:
  push:
    tags:
       - '*'

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v2
      run: docker build . --file Dockerfile --tag yabramkin/aws-cdk-runtime-environment-win:${GITHUB_REF##*/}
